/**
 * Every error `src/core` throws, with the judgement a generator cannot supply.
 *
 * The **message** of each entry is checked against the `throw` sites in `src/core`
 * by `src/tests/docs/coreLogs.test.ts`, in both directions: a new `throw` that is
 * not declared here fails the test, and a declaration nothing throws fails it too.
 * What cannot be read from the source — recoverable or fatal, the cause, the fix —
 * is written by hand, because `.claude/rules/guide.md` forbids documenting an error
 * without it.
 *
 * The core layer differs from a feature in one way worth knowing before reading the
 * page it produces: most of these throws are **caught by core itself**. A reader
 * chasing a broken page needs to know whether an error reached them or was swallowed
 * and logged, so every entry that is caught says so in {@link CoreErrorDoc.caught}
 * and names the log line it turns into — which is in
 * [logs.md](../guide/reference/logs.md).
 *
 * Build-time only, like `sdk-attributes.ts`: nothing under
 * `src/` may import this, or the prose ships in the bundle that loads on customer
 * landing pages.
 */

import type { ErrorDoc } from '../schema/doc-types';

/** One error thrown somewhere in `src/core`. */
export interface CoreErrorDoc extends ErrorDoc {
  /**
   * The subsystem that throws it, as the logger prefix a reader sees in the console
   * — `SDKInitializer`, `CountryService`. Matches a `prefix` in `core-logs.ts` so the
   * two pages line up.
   */
  owner: string;
  /**
   * Path of the throwing file, relative to `src/core`. Checked against the source, so
   * an error that moves to another file cannot keep a stale location on the page.
   */
  file: string;
  /**
   * What catches it and what the visitor is left with. Omit for an error that
   * genuinely propagates to the caller — then the page says the caller sees it.
   */
  caught?: string;
  /**
   * The message as `extract-logs.ts` renders it, for the few throws where that reads
   * worse than the truth.
   *
   * The extractor turns a `${…}` into `{lastDotSegment}`, which is right for
   * `${this.selectorId}` → `{selectorId}` and wrong for a ternary: `${error instanceof
   * Error ? error.message : String(error)}` comes out as `{message : String(error)}`,
   * which is not something a reader would ever type into a search box. Set this to that
   * exact string and put the readable form in {@link ErrorDoc.message} — the drift check
   * uses this one, so the tie to the source is unchanged, and the page shows the other.
   */
  extracted?: string;
}

/**
 * Fatal versus recoverable follows {@link ErrorDoc.kind}: `recoverable` means a retry
 * or a corrected input gets past it with no code change; `fatal` means it recurs until
 * markup, code, or configuration changes.
 */
export const CORE_ERRORS: CoreErrorDoc[] = [
  // ── Boot ───────────────────────────────────────────────────────────────────
  {
    message:
      'API key not found. Please set next-api-key meta tag or window.nextConfig.apiKey',
    owner: 'SDKInitializer',
    file: 'sdk-initializer/sdk-initializer.ts',
    kind: 'fatal',
    cause:
      'Boot reached the campaign load with no API key in the config store — neither the `next-api-key` meta tag nor `window.nextConfig.apiKey` was set before the loader ran.',
    caught:
      '`SDKInitializer.initialize()` catches it, logs `SDK initialization failed:`, retries up to three times, then gives up. Every price, product name, and cart total stays at its placeholder, because none of them exist without campaign data.',
    fix: `Add the key to the page head, above the SDK loader script:

\`\`\`html
<meta name="next-api-key" content="{YOUR_CAMPAIGN_API_KEY}" />
<!-- the SDK loader script goes after this -->
\`\`\`

Or set it in configuration, again before the loader:

\`\`\`html
<script>
  window.nextConfig = { apiKey: '{YOUR_CAMPAIGN_API_KEY}' };
</script>
\`\`\`

Setting it *after* the loader is too late — the campaign request has already been made.`,
  },
  {
    message: 'Invalid package ID: {idStr}',
    owner: 'SDKInitializer',
    file: 'sdk-initializer/sdk-initializer.url-params.ts',
    kind: 'fatal',
    cause:
      'The `forcePackageId` URL parameter contains something that is not a positive whole number — a typo, a template token that was never substituted (`forcePackageId={{package}}`), or a stray separator such as `forcePackageId=12,,13`.',
    caught:
      'The `forcePackageId` handler catches it and logs `Error processing forcePackageId parameter:`. Boot continues, and **no** package from that parameter is added — including the ones that parsed correctly, because the whole list is parsed before anything is added.',
    fix: `Write the parameter as \`id\` or \`id:quantity\`, comma-separated:

\`\`\`text
?forcePackageId=42
?forcePackageId=42:2,57:1
\`\`\`

If the link is generated by an ad platform or an email tool, check that the token was substituted before the click.`,
  },
  {
    message: 'Invalid quantity: {quantityStr}',
    owner: 'SDKInitializer',
    file: 'sdk-initializer/sdk-initializer.url-params.ts',
    kind: 'fatal',
    cause:
      'The quantity half of a `forcePackageId` entry is not a positive whole number — `?forcePackageId=42:0` or `?forcePackageId=42:two`.',
    caught:
      'Same as `Invalid package ID` — caught by the `forcePackageId` handler, logged as `Error processing forcePackageId parameter:`, and no package from the parameter reaches the cart.',
    fix: 'Use a whole number of 1 or more (`?forcePackageId=42:2`). To put nothing in the cart, leave the parameter off rather than passing a quantity of `0`.',
  },
  {
    message: 'Invalid shipping ID: {forceShippingId}',
    owner: 'SDKInitializer',
    file: 'sdk-initializer/sdk-initializer.url-params.ts',
    kind: 'fatal',
    cause:
      'The `forceShippingId` URL parameter is not a positive whole number.',
    caught:
      'The `forceShippingId` handler catches it and logs `Error processing forceShippingId parameter:`. Boot continues with whatever shipping method the cart already had, which on a fresh session is none.',
    fix: 'Pass the shipping method `ref_id` as a number — `?forceShippingId=3`. The available ids are listed in the debug log `Available shipping methods:` and in the campaign data under `shipping_methods`.',
  },

  // ── Shared base class ──────────────────────────────────────────────────────
  {
    message: 'Required attribute {name} not found on element',
    owner: '{EnhancerClassName}',
    file: 'base/base-enhancer.ts',
    kind: 'fatal',
    cause:
      'A feature asked for an attribute it cannot work without and the element does not carry it, or carries it empty (`data-next-package-id=""` counts as missing). Every feature inherits this check from the shared base class, so the message can come from any of them — the logger prefix in the console tells you which.',
    caught:
      '`AttributeScanner` catches it, logs `Failed to initialize {type} enhancer:` with the element, and destroys the half-built feature. That element stays plain markup: a button does nothing on click, a display element keeps its placeholder text. The rest of the page is enhanced normally.',
    fix: 'Add the named attribute to the element. The attributes each feature requires are in the [data attributes reference](../../../../docs/guides/reference/data-attributes.md). Check for an empty value as well as a missing one, since both raise this.',
  },
  {
    message: 'Element is required',
    owner: '{EnhancerClassName}',
    file: 'base/base-enhancer.ts',
    kind: 'fatal',
    cause:
      'A feature was constructed with no element. Markup cannot cause this — `AttributeScanner` only ever constructs a feature for an element it found — so it means code built one by hand and passed a `null` from a `querySelector` that matched nothing.',
    caught:
      'Nothing in core catches it: it propagates to whoever called the constructor.',
    fix: `Resolve the element before constructing, and stop if it is not there:

\`\`\`ts
const el = document.querySelector<HTMLElement>('[data-next-checkout]');
if (!el) return; // nothing to enhance
new CheckoutFormEnhancer(el);
\`\`\`

In almost every case the better answer is to add the feature's \`data-next-*\` attribute to the markup and let \`AttributeScanner\` construct it.`,
  },

  // ── Country service ────────────────────────────────────────────────────────
  {
    message: '{url} carried no address layout',
    owner: 'CountryService',
    file: 'country-service/country-service.next-address.ts',
    kind: 'recoverable',
    cause:
      'The address service answered, but the body had no list of address rows in it. A proxy or a captive portal returning an HTML page in place of the JSON is the realistic cause.',
    caught:
      'Caught by `CountryService` like any other failed lookup: it logs `Failed to fetch location data:` or `Failed to fetch states for {countryCode}:` and continues with the built-in fallback — the country list from configuration, United States as the country, and an empty state list with default labels.',
    fix: 'Open the URL from the message directly and confirm it answers JSON carrying `spec.layout`. Reaching it through a network that rewrites responses is what produces this.',
  },
  {
    message: '{url} responded {status} {statusText}',
    owner: 'CountryService',
    file: 'country-service/country-service.next-address.ts',
    kind: 'recoverable',
    cause:
      'The address service answered with a non-OK status while the SDK was asking for the country list or one country’s address rules. The visitor’s network, an extension, or the service being briefly unavailable all produce this. An unknown country code is not a cause: an uncurated country is answered with a generic layout.',
    caught:
      'Caught by `CountryService`, which logs `Failed to fetch location data:` or `Failed to fetch states for {countryCode}:` and continues with its built-in fallback — the country list from configuration, United States as the country, and an empty state list with default labels. Checkout still works; the country dropdown is shorter than it should be, and a visitor in a country that requires a state cannot pick one.',
    fix: 'Nothing to change in the page. If it is not intermittent, check that the address host is reachable from the visitor’s network, then reload — a good answer is cached in localStorage for an hour, so one fixes the session.',
  },

  // ── window.next API ────────────────────────────────────────────────────────
  {
    message:
      'No order found. Upsells can only be added after order completion.',
    owner: 'NextCommerce',
    file: 'next-commerce/next-commerce.upsells.ts',
    kind: 'fatal',
    cause:
      '`next.addUpsell()` was called with no order in the order store. Either the page is not a post-purchase page, or it is one but the order has not finished loading yet.',
    caught:
      'Nothing catches it — it rejects the promise `next.addUpsell()` returned, so your own `catch` sees it.',
    fix: `Call it only after the order is loaded. On a receipt or upsell page the SDK loads the order from the \`ref_id\` URL parameter during boot, so waiting for \`next:ready\` is enough:

\`\`\`ts
window.nextReady = window.nextReady || [];
window.nextReady.push(async next => {
  await next.addUpsell({ packageId: 42, quantity: 1 });
});
\`\`\`

If the page has no \`?ref_id=\`, there is no order to add to and no amount of waiting will produce one.`,
  },
  {
    message:
      'Order does not support post-purchase upsells or is currently processing.',
    owner: 'NextCommerce',
    file: 'next-commerce/next-commerce.upsells.ts',
    kind: 'recoverable',
    cause:
      'Two different situations share this message. Either the order came back with `supports_post_purchase_upsells: false` — the payment method or the campaign does not allow adding to a completed order — or another upsell request is still in flight.',
    caught: 'Nothing catches it — the promise from `next.addUpsell()` rejects.',
    fix: 'For the in-flight case, wait for the previous call to settle and try again; disabling the accept button while a request is running prevents it. For the unsupported case, hide the upsell offer instead of letting a visitor accept something that cannot be added — read `supports_post_purchase_upsells` on the order, which boot logs as `Order supports upsells:`.',
  },
  {
    message: 'Either packageId or items array must be provided',
    owner: 'NextCommerce',
    file: 'next-commerce/next-commerce.upsells.ts',
    kind: 'fatal',
    cause:
      '`next.addUpsell()` was called with neither `packageId` nor a non-empty `items` array — often an options object built from a variable that turned out to be `undefined`.',
    caught: 'Nothing catches it — the promise rejects.',
    fix: `Pass one package or a list of them:

\`\`\`ts
await next.addUpsell({ packageId: 42, quantity: 1 });
await next.addUpsell({ items: [{ packageId: 42, quantity: 1 }, { packageId: 57 }] });
\`\`\`

An \`items: []\` is treated as nothing provided, so guard an empty selection before calling.`,
  },
  {
    message: 'Failed to add upsell - no updated order returned',
    owner: 'NextCommerce',
    file: 'next-commerce/next-commerce.upsells.ts',
    kind: 'recoverable',
    cause:
      'The upsell request completed but the order store had no updated order to return.',
    caught: 'Nothing catches it — the promise rejects.',
    fix: 'Treat this as "outcome unknown", not as a failure: the line may well have been added and the visitor charged. Re-read the order before offering a retry, or the visitor can be charged twice for the same upsell. If it reproduces, it is a backend contract problem rather than a markup one.',
  },

  // ── Test mode ──────────────────────────────────────────────────────────────
  {
    message: 'No test cards available',
    owner: 'SDK test mode',
    file: 'test-mode.ts',
    kind: 'fatal',
    cause:
      'Test mode was asked for a card to fill the checkout form with and its list was empty.',
    caught:
      'Nothing catches it — it propagates to the caller, which is test-mode code, not a customer page.',
    fix: 'A shipped build cannot reach this: the card list is a constant with several entries. It guards against that list being emptied, so seeing it means `test-mode.ts` was edited. Restore an entry in `testCards`.',
  },

  // ── Analytics providers ────────────────────────────────────────────────────
  {
    message: 'HTTP {status}: {statusText}',
    owner: 'Custom',
    file: 'analytics/providers/custom-adapter.ts',
    kind: 'recoverable',
    cause:
      'The custom analytics endpoint answered a batch of events with a non-OK status.',
    caught:
      'Caught by the adapter, which logs `Error sending batch to custom endpoint:` and puts every event in the batch on its retry queue. After the configured number of attempts it gives up with `Failed to send event after {maxRetries} attempts:`.',
    fix: 'Check the endpoint URL and its response for the status in the message. Nothing on the page breaks — only the events for this one provider are lost, and only after the retries are exhausted.',
  },
  {
    message: 'Facebook Pixel load timeout',
    owner: 'Facebook',
    file: 'analytics/providers/facebook-adapter.ts',
    kind: 'recoverable',
    cause:
      '`fbq` never appeared on the page within the adapter’s wait, so there was nothing to deliver the event to. The Meta Pixel base code is missing, or an extension blocked it.',
    caught:
      'Thrown as a `DispatchError`, which the shared adapter base treats as an expected delivery outcome: it logs the warn `Event "{event}" not delivered: Facebook Pixel load timeout` and records the payload it would have sent in the debug overlay. The visitor sees nothing.',
    fix: 'Add the Meta Pixel base code to the page, above the SDK loader. The adapter also warns once with the fix in it — `Meta Pixel (fbq) not found …`. If the pixel is present, check whether an ad blocker removed it before deciding the SDK is at fault.',
  },
  {
    message: 'Facebook dispatch failed: {message}',
    extracted: 'Facebook dispatch failed: {message : String(error)}',
    owner: 'Facebook',
    file: 'analytics/providers/facebook-adapter.ts',
    kind: 'recoverable',
    cause:
      '`fbq` was on the page but threw when the event was handed to it. The message after the colon is whatever the pixel raised.',
    caught:
      'A `DispatchError`, so the adapter base logs `Event "{event}" not delivered: Facebook dispatch failed: …` and records the attempted payload. One provider failing never stops the others.',
    fix: 'Read the message after the colon — it comes from the pixel, not from the SDK. A parameter the pixel rejects is the usual cause; the attempted payload is in the debug overlay’s Provider Delivery panel (`?debug=true`).',
  },
  {
    message: 'NextCampaign SDK load failed',
    owner: 'NextCampaign',
    file: 'analytics/providers/next-campaign-adapter.ts',
    kind: 'recoverable',
    cause:
      'The NextCampaign script never loaded, so its `page_view` could not be delivered. A missing API key or an unreachable campaigns host both produce this.',
    caught:
      'A `DispatchError`: the adapter base logs `Event "{event}" not delivered: NextCampaign SDK load failed` and keeps the prepared payload for the debug overlay.',
    fix: 'Confirm the API key is set (the adapter logs `API key from config store: found` when it is) and that `campaigns.apps.29next.com` is reachable. The adapter also warns once with the same fix — `NextCampaign SDK failed to load …`.',
  },
  {
    message: 'NextCampaign dispatch failed: {message}',
    extracted: 'NextCampaign dispatch failed: {message : String(error)}',
    owner: 'NextCampaign',
    file: 'analytics/providers/next-campaign-adapter.ts',
    kind: 'recoverable',
    cause:
      'The NextCampaign script was loaded but threw when the event was handed to it. The text after the colon is its own message.',
    caught:
      'A `DispatchError`, logged by the adapter base as `Event "{event}" not delivered: NextCampaign dispatch failed: …`.',
    fix: 'Read the message after the colon; it comes from the NextCampaign script. The event payload that was attempted is in the debug overlay’s Provider Delivery panel (`?debug=true`).',
  },
  {
    message: 'RudderStack load timeout',
    owner: 'RudderStack',
    file: 'analytics/providers/rudderstack-adapter.ts',
    kind: 'recoverable',
    cause:
      '`rudderanalytics` never appeared on the page within the adapter’s wait, so the event had nowhere to go.',
    caught:
      'A `DispatchError`: the adapter base logs `Event "{event}" not delivered: RudderStack load timeout` and records the descriptor it had prepared.',
    fix: 'Add the RudderStack JavaScript SDK snippet to the page, above the SDK loader. The adapter warns once with the same instruction — `rudderanalytics not found …`.',
  },

  // ── Shared base ────────────────────────────────────────────────────────────
  {
    // `{name}` is how the extractor renders `${this.constructor.name}` — at runtime it
    // is the concrete subclass, e.g. `ProductDisplayEnhancer: data-next-display …`.
    message: '{name}: data-next-display attribute is required',
    owner: '{DisplayEnhancerClassName}',
    file: 'base/base-display-enhancer.ts',
    kind: 'fatal',
    cause:
      'An element was matched as a display binding but carries no `data-next-display` value to bind. Almost always the attribute is present with an empty value (`data-next-display=""`), or a templating step emitted the name without filling it in — a genuinely absent attribute would not have matched in the first place.',
    caught:
      'The base feature class catches it, logs it under the failing feature’s own prefix, and emits `error:occurred`. Only that element is affected: it keeps its placeholder text and never updates, while every other binding on the page works normally.',
    fix: `Give the element a namespaced path, or remove the attribute if the element is not a display binding:

\`\`\`html
<!-- was: <span data-next-display=""></span> -->
<span data-next-display="cart.total"></span>
\`\`\`

The namespace before the dot decides which part of the SDK answers — see the [data attributes reference](../../../../docs/guides/reference/data-attributes.md) for the full list.`,
  },
];
